package main

const (
	// MaxIdleConnections ...
	MaxIdleConnections = "maxIdleConnections"
	// RequestTimeout ...
	RequestTimeout = "requestTimeout"
	// CheckEveryMinutes ...
	CheckEveryMinutes = "checkEveryMinutes"
	// AllowedConsecutiveErrorsBeforePanic ...
	AllowedConsecutiveErrorsBeforePanic = "allowedConsecutiveErrorsBeforePanic"
	// EmailTo ...
	EmailTo = "emailTo"
	// SendGridAPIKey ...
	SendGridAPIKey = "sendGridApiKey"
)
